#############################################################################
# Makefile for building: harmonyqml
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  harmonyqml.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile harmonyqml.pro CONFIG+=no_embedded
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -w -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -w -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isubmodules/SortFilterProxyModel -I /usr/include/qt5 -I /usr/include/qt5/QtQuick -I /usr/include/qt5/QtGui -I /usr/include/qt5/QtQml -I /usr/include/qt5/QtNetwork -I /usr/include/qt5/QtCore -Ibuild/moc -I /usr/include/libdrm -I/usr/lib/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -rf
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -rf
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = harmonyqml1.0.0
DISTDIR = /home/kana/prog/python/harmonyqml/build/obj/harmonyqml1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS) -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp \
		submodules/SortFilterProxyModel/filters/filter.cpp \
		submodules/SortFilterProxyModel/filters/filtercontainer.cpp \
		submodules/SortFilterProxyModel/filters/rolefilter.cpp \
		submodules/SortFilterProxyModel/filters/valuefilter.cpp \
		submodules/SortFilterProxyModel/filters/indexfilter.cpp \
		submodules/SortFilterProxyModel/filters/regexpfilter.cpp \
		submodules/SortFilterProxyModel/filters/rangefilter.cpp \
		submodules/SortFilterProxyModel/filters/expressionfilter.cpp \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.cpp \
		submodules/SortFilterProxyModel/filters/anyoffilter.cpp \
		submodules/SortFilterProxyModel/filters/alloffilter.cpp \
		submodules/SortFilterProxyModel/filters/filtersqmltypes.cpp \
		submodules/SortFilterProxyModel/sorters/sorter.cpp \
		submodules/SortFilterProxyModel/sorters/sortercontainer.cpp \
		submodules/SortFilterProxyModel/sorters/rolesorter.cpp \
		submodules/SortFilterProxyModel/sorters/stringsorter.cpp \
		submodules/SortFilterProxyModel/sorters/expressionsorter.cpp \
		submodules/SortFilterProxyModel/sorters/sortersqmltypes.cpp \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.cpp \
		submodules/SortFilterProxyModel/proxyroles/joinrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/switchrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/expressionrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/proxyrolesqmltypes.cpp \
		submodules/SortFilterProxyModel/proxyroles/singlerole.cpp \
		submodules/SortFilterProxyModel/proxyroles/regexprole.cpp \
		submodules/SortFilterProxyModel/sorters/filtersorter.cpp \
		submodules/SortFilterProxyModel/proxyroles/filterrole.cpp build/moc/moc_qqmlsortfilterproxymodel.cpp \
		build/moc/moc_filter.cpp \
		build/moc/moc_rolefilter.cpp \
		build/moc/moc_valuefilter.cpp \
		build/moc/moc_indexfilter.cpp \
		build/moc/moc_regexpfilter.cpp \
		build/moc/moc_rangefilter.cpp \
		build/moc/moc_expressionfilter.cpp \
		build/moc/moc_filtercontainerfilter.cpp \
		build/moc/moc_anyoffilter.cpp \
		build/moc/moc_alloffilter.cpp \
		build/moc/moc_sorter.cpp \
		build/moc/moc_rolesorter.cpp \
		build/moc/moc_stringsorter.cpp \
		build/moc/moc_expressionsorter.cpp \
		build/moc/moc_proxyrole.cpp \
		build/moc/moc_joinrole.cpp \
		build/moc/moc_switchrole.cpp \
		build/moc/moc_expressionrole.cpp \
		build/moc/moc_singlerole.cpp \
		build/moc/moc_regexprole.cpp \
		build/moc/moc_filtersorter.cpp \
		build/moc/moc_filterrole.cpp
OBJECTS       = build/obj/main.o \
		build/obj/qqmlsortfilterproxymodel.o \
		build/obj/filter.o \
		build/obj/filtercontainer.o \
		build/obj/rolefilter.o \
		build/obj/valuefilter.o \
		build/obj/indexfilter.o \
		build/obj/regexpfilter.o \
		build/obj/rangefilter.o \
		build/obj/expressionfilter.o \
		build/obj/filtercontainerfilter.o \
		build/obj/anyoffilter.o \
		build/obj/alloffilter.o \
		build/obj/filtersqmltypes.o \
		build/obj/sorter.o \
		build/obj/sortercontainer.o \
		build/obj/rolesorter.o \
		build/obj/stringsorter.o \
		build/obj/expressionsorter.o \
		build/obj/sortersqmltypes.o \
		build/obj/proxyrole.o \
		build/obj/proxyrolecontainer.o \
		build/obj/joinrole.o \
		build/obj/switchrole.o \
		build/obj/expressionrole.o \
		build/obj/proxyrolesqmltypes.o \
		build/obj/singlerole.o \
		build/obj/regexprole.o \
		build/obj/filtersorter.o \
		build/obj/filterrole.o \
		build/obj/moc_qqmlsortfilterproxymodel.o \
		build/obj/moc_filter.o \
		build/obj/moc_rolefilter.o \
		build/obj/moc_valuefilter.o \
		build/obj/moc_indexfilter.o \
		build/obj/moc_regexpfilter.o \
		build/obj/moc_rangefilter.o \
		build/obj/moc_expressionfilter.o \
		build/obj/moc_filtercontainerfilter.o \
		build/obj/moc_anyoffilter.o \
		build/obj/moc_alloffilter.o \
		build/obj/moc_sorter.o \
		build/obj/moc_rolesorter.o \
		build/obj/moc_stringsorter.o \
		build/obj/moc_expressionsorter.o \
		build/obj/moc_proxyrole.o \
		build/obj/moc_joinrole.o \
		build/obj/moc_switchrole.o \
		build/obj/moc_expressionrole.o \
		build/obj/moc_singlerole.o \
		build/obj/moc_regexprole.o \
		build/obj/moc_filtersorter.o \
		build/obj/moc_filterrole.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		submodules/SortFilterProxyModel/SortFilterProxyModel.pri \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		harmonyqml.pro submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/valuefilter.h \
		submodules/SortFilterProxyModel/filters/indexfilter.h \
		submodules/SortFilterProxyModel/filters/regexpfilter.h \
		submodules/SortFilterProxyModel/filters/rangefilter.h \
		submodules/SortFilterProxyModel/filters/expressionfilter.h \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/anyoffilter.h \
		submodules/SortFilterProxyModel/filters/alloffilter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/sorters/rolesorter.h \
		submodules/SortFilterProxyModel/sorters/stringsorter.h \
		submodules/SortFilterProxyModel/sorters/expressionsorter.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h \
		submodules/SortFilterProxyModel/proxyroles/joinrole.h \
		submodules/SortFilterProxyModel/proxyroles/switchrole.h \
		submodules/SortFilterProxyModel/proxyroles/expressionrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/regexprole.h \
		submodules/SortFilterProxyModel/sorters/filtersorter.h \
		submodules/SortFilterProxyModel/proxyroles/filterrole.h src/main.cpp \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp \
		submodules/SortFilterProxyModel/filters/filter.cpp \
		submodules/SortFilterProxyModel/filters/filtercontainer.cpp \
		submodules/SortFilterProxyModel/filters/rolefilter.cpp \
		submodules/SortFilterProxyModel/filters/valuefilter.cpp \
		submodules/SortFilterProxyModel/filters/indexfilter.cpp \
		submodules/SortFilterProxyModel/filters/regexpfilter.cpp \
		submodules/SortFilterProxyModel/filters/rangefilter.cpp \
		submodules/SortFilterProxyModel/filters/expressionfilter.cpp \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.cpp \
		submodules/SortFilterProxyModel/filters/anyoffilter.cpp \
		submodules/SortFilterProxyModel/filters/alloffilter.cpp \
		submodules/SortFilterProxyModel/filters/filtersqmltypes.cpp \
		submodules/SortFilterProxyModel/sorters/sorter.cpp \
		submodules/SortFilterProxyModel/sorters/sortercontainer.cpp \
		submodules/SortFilterProxyModel/sorters/rolesorter.cpp \
		submodules/SortFilterProxyModel/sorters/stringsorter.cpp \
		submodules/SortFilterProxyModel/sorters/expressionsorter.cpp \
		submodules/SortFilterProxyModel/sorters/sortersqmltypes.cpp \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.cpp \
		submodules/SortFilterProxyModel/proxyroles/joinrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/switchrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/expressionrole.cpp \
		submodules/SortFilterProxyModel/proxyroles/proxyrolesqmltypes.cpp \
		submodules/SortFilterProxyModel/proxyroles/singlerole.cpp \
		submodules/SortFilterProxyModel/proxyroles/regexprole.cpp \
		submodules/SortFilterProxyModel/sorters/filtersorter.cpp \
		submodules/SortFilterProxyModel/proxyroles/filterrole.cpp
QMAKE_TARGET  = harmonyqml
DESTDIR       = 
TARGET        = harmonyqml


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: harmonyqml.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		submodules/SortFilterProxyModel/SortFilterProxyModel.pri \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		harmonyqml.pro \
		/usr/lib64/libQt5Quick.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Qml.prl \
		/usr/lib64/libQt5Network.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile harmonyqml.pro CONFIG+=no_embedded
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
submodules/SortFilterProxyModel/SortFilterProxyModel.pri:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_off.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
harmonyqml.pro:
/usr/lib64/libQt5Quick.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Qml.prl:
/usr/lib64/libQt5Network.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile harmonyqml.pro CONFIG+=no_embedded

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h submodules/SortFilterProxyModel/filters/filter.h submodules/SortFilterProxyModel/filters/filtercontainer.h submodules/SortFilterProxyModel/filters/rolefilter.h submodules/SortFilterProxyModel/filters/valuefilter.h submodules/SortFilterProxyModel/filters/indexfilter.h submodules/SortFilterProxyModel/filters/regexpfilter.h submodules/SortFilterProxyModel/filters/rangefilter.h submodules/SortFilterProxyModel/filters/expressionfilter.h submodules/SortFilterProxyModel/filters/filtercontainerfilter.h submodules/SortFilterProxyModel/filters/anyoffilter.h submodules/SortFilterProxyModel/filters/alloffilter.h submodules/SortFilterProxyModel/sorters/sorter.h submodules/SortFilterProxyModel/sorters/sortercontainer.h submodules/SortFilterProxyModel/sorters/rolesorter.h submodules/SortFilterProxyModel/sorters/stringsorter.h submodules/SortFilterProxyModel/sorters/expressionsorter.h submodules/SortFilterProxyModel/proxyroles/proxyrole.h submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h submodules/SortFilterProxyModel/proxyroles/joinrole.h submodules/SortFilterProxyModel/proxyroles/switchrole.h submodules/SortFilterProxyModel/proxyroles/expressionrole.h submodules/SortFilterProxyModel/proxyroles/singlerole.h submodules/SortFilterProxyModel/proxyroles/regexprole.h submodules/SortFilterProxyModel/sorters/filtersorter.h submodules/SortFilterProxyModel/proxyroles/filterrole.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp submodules/SortFilterProxyModel/filters/filter.cpp submodules/SortFilterProxyModel/filters/filtercontainer.cpp submodules/SortFilterProxyModel/filters/rolefilter.cpp submodules/SortFilterProxyModel/filters/valuefilter.cpp submodules/SortFilterProxyModel/filters/indexfilter.cpp submodules/SortFilterProxyModel/filters/regexpfilter.cpp submodules/SortFilterProxyModel/filters/rangefilter.cpp submodules/SortFilterProxyModel/filters/expressionfilter.cpp submodules/SortFilterProxyModel/filters/filtercontainerfilter.cpp submodules/SortFilterProxyModel/filters/anyoffilter.cpp submodules/SortFilterProxyModel/filters/alloffilter.cpp submodules/SortFilterProxyModel/filters/filtersqmltypes.cpp submodules/SortFilterProxyModel/sorters/sorter.cpp submodules/SortFilterProxyModel/sorters/sortercontainer.cpp submodules/SortFilterProxyModel/sorters/rolesorter.cpp submodules/SortFilterProxyModel/sorters/stringsorter.cpp submodules/SortFilterProxyModel/sorters/expressionsorter.cpp submodules/SortFilterProxyModel/sorters/sortersqmltypes.cpp submodules/SortFilterProxyModel/proxyroles/proxyrole.cpp submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.cpp submodules/SortFilterProxyModel/proxyroles/joinrole.cpp submodules/SortFilterProxyModel/proxyroles/switchrole.cpp submodules/SortFilterProxyModel/proxyroles/expressionrole.cpp submodules/SortFilterProxyModel/proxyroles/proxyrolesqmltypes.cpp submodules/SortFilterProxyModel/proxyroles/singlerole.cpp submodules/SortFilterProxyModel/proxyroles/regexprole.cpp submodules/SortFilterProxyModel/sorters/filtersorter.cpp submodules/SortFilterProxyModel/proxyroles/filterrole.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) build/moc build/obj build/rcc src/python/__pycache__ src/python/events/__pycache__ build/resources.qrc build Makefile .qmake.stash src/python/__pycache__/__about__.cpython-36.pyc src/python/__pycache__/__init__.cpython-36.pyc src/python/__pycache__/app.cpython-36.pyc src/python/__pycache__/backend.cpython-36.pyc src/python/__pycache__/html_filter.cpython-36.pyc src/python/__pycache__/matrix_client.cpython-36.pyc src/python/events/__pycache__/__init__.cpython-36.pyc src/python/events/__pycache__/app.cpython-36.pyc src/python/events/__pycache__/event.cpython-36.pyc src/python/events/__pycache__/rooms.cpython-36.pyc src/python/events/__pycache__/rooms_timeline.cpython-36.pyc src/python/events/__pycache__/timeline.cpython-36.pyc src/python/events/__pycache__/users.cpython-36.pyc
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -w -dM -E -o build/moc/moc_predefs.h /usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_qqmlsortfilterproxymodel.cpp build/moc/moc_filter.cpp build/moc/moc_rolefilter.cpp build/moc/moc_valuefilter.cpp build/moc/moc_indexfilter.cpp build/moc/moc_regexpfilter.cpp build/moc/moc_rangefilter.cpp build/moc/moc_expressionfilter.cpp build/moc/moc_filtercontainerfilter.cpp build/moc/moc_anyoffilter.cpp build/moc/moc_alloffilter.cpp build/moc/moc_sorter.cpp build/moc/moc_rolesorter.cpp build/moc/moc_stringsorter.cpp build/moc/moc_expressionsorter.cpp build/moc/moc_proxyrole.cpp build/moc/moc_joinrole.cpp build/moc/moc_switchrole.cpp build/moc/moc_expressionrole.cpp build/moc/moc_singlerole.cpp build/moc/moc_regexprole.cpp build/moc/moc_filtersorter.cpp build/moc/moc_filterrole.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_qqmlsortfilterproxymodel.cpp build/moc/moc_filter.cpp build/moc/moc_rolefilter.cpp build/moc/moc_valuefilter.cpp build/moc/moc_indexfilter.cpp build/moc/moc_regexpfilter.cpp build/moc/moc_rangefilter.cpp build/moc/moc_expressionfilter.cpp build/moc/moc_filtercontainerfilter.cpp build/moc/moc_anyoffilter.cpp build/moc/moc_alloffilter.cpp build/moc/moc_sorter.cpp build/moc/moc_rolesorter.cpp build/moc/moc_stringsorter.cpp build/moc/moc_expressionsorter.cpp build/moc/moc_proxyrole.cpp build/moc/moc_joinrole.cpp build/moc/moc_switchrole.cpp build/moc/moc_expressionrole.cpp build/moc/moc_singlerole.cpp build/moc/moc_regexprole.cpp build/moc/moc_filtersorter.cpp build/moc/moc_filterrole.cpp
build/moc/moc_qqmlsortfilterproxymodel.cpp: submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h -o build/moc/moc_qqmlsortfilterproxymodel.cpp

build/moc/moc_filter.cpp: submodules/SortFilterProxyModel/filters/filter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/filter.h -o build/moc/moc_filter.cpp

build/moc/moc_rolefilter.cpp: submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/rolefilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/rolefilter.h -o build/moc/moc_rolefilter.cpp

build/moc/moc_valuefilter.cpp: submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/valuefilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/valuefilter.h -o build/moc/moc_valuefilter.cpp

build/moc/moc_indexfilter.cpp: submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/indexfilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/indexfilter.h -o build/moc/moc_indexfilter.cpp

build/moc/moc_regexpfilter.cpp: submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/regexpfilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/regexpfilter.h -o build/moc/moc_regexpfilter.cpp

build/moc/moc_rangefilter.cpp: submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/rangefilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/rangefilter.h -o build/moc/moc_rangefilter.cpp

build/moc/moc_expressionfilter.cpp: submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/expressionfilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/expressionfilter.h -o build/moc/moc_expressionfilter.cpp

build/moc/moc_filtercontainerfilter.cpp: submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/filtercontainerfilter.h -o build/moc/moc_filtercontainerfilter.cpp

build/moc/moc_anyoffilter.cpp: submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/anyoffilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/anyoffilter.h -o build/moc/moc_anyoffilter.cpp

build/moc/moc_alloffilter.cpp: submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/alloffilter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/filters/alloffilter.h -o build/moc/moc_alloffilter.cpp

build/moc/moc_sorter.cpp: submodules/SortFilterProxyModel/sorters/sorter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/sorters/sorter.h -o build/moc/moc_sorter.cpp

build/moc/moc_rolesorter.cpp: submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/sorters/rolesorter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/sorters/rolesorter.h -o build/moc/moc_rolesorter.cpp

build/moc/moc_stringsorter.cpp: submodules/SortFilterProxyModel/sorters/rolesorter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/sorters/stringsorter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/sorters/stringsorter.h -o build/moc/moc_stringsorter.cpp

build/moc/moc_expressionsorter.cpp: submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/sorters/expressionsorter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/sorters/expressionsorter.h -o build/moc/moc_expressionsorter.cpp

build/moc/moc_proxyrole.cpp: submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/proxyrole.h -o build/moc/moc_proxyrole.cpp

build/moc/moc_joinrole.cpp: submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/proxyroles/joinrole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/joinrole.h -o build/moc/moc_joinrole.cpp

build/moc/moc_switchrole.cpp: submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/switchrole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/switchrole.h -o build/moc/moc_switchrole.cpp

build/moc/moc_expressionrole.cpp: submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/proxyroles/expressionrole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/expressionrole.h -o build/moc/moc_expressionrole.cpp

build/moc/moc_singlerole.cpp: submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/singlerole.h -o build/moc/moc_singlerole.cpp

build/moc/moc_regexprole.cpp: submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/proxyroles/regexprole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/regexprole.h -o build/moc/moc_regexprole.cpp

build/moc/moc_filtersorter.cpp: submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/filtersorter.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/sorters/filtersorter.h -o build/moc/moc_filtersorter.cpp

build/moc/moc_filterrole.cpp: submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/filterrole.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kana/prog/python/harmonyqml/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/kana/prog/python/harmonyqml -I/home/kana/prog/python/harmonyqml/submodules/SortFilterProxyModel -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/include/c++/9.1.0 -I/usr/include/c++/9.1.0/x86_64-unknown-linux-gnu -I/usr/include/c++/9.1.0/backward -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-unknown-linux-gnu/9.1.0/include-fixed -I/usr/include submodules/SortFilterProxyModel/proxyroles/filterrole.h -o build/moc/moc_filterrole.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/qqmlsortfilterproxymodel.o: submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qqmlsortfilterproxymodel.o submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp

build/obj/filter.o: submodules/SortFilterProxyModel/filters/filter.cpp submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filter.o submodules/SortFilterProxyModel/filters/filter.cpp

build/obj/filtercontainer.o: submodules/SortFilterProxyModel/filters/filtercontainer.cpp submodules/SortFilterProxyModel/filters/filtercontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filtercontainer.o submodules/SortFilterProxyModel/filters/filtercontainer.cpp

build/obj/rolefilter.o: submodules/SortFilterProxyModel/filters/rolefilter.cpp submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/rolefilter.o submodules/SortFilterProxyModel/filters/rolefilter.cpp

build/obj/valuefilter.o: submodules/SortFilterProxyModel/filters/valuefilter.cpp submodules/SortFilterProxyModel/filters/valuefilter.h \
		submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/valuefilter.o submodules/SortFilterProxyModel/filters/valuefilter.cpp

build/obj/indexfilter.o: submodules/SortFilterProxyModel/filters/indexfilter.cpp submodules/SortFilterProxyModel/filters/indexfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/indexfilter.o submodules/SortFilterProxyModel/filters/indexfilter.cpp

build/obj/regexpfilter.o: submodules/SortFilterProxyModel/filters/regexpfilter.cpp submodules/SortFilterProxyModel/filters/regexpfilter.h \
		submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/regexpfilter.o submodules/SortFilterProxyModel/filters/regexpfilter.cpp

build/obj/rangefilter.o: submodules/SortFilterProxyModel/filters/rangefilter.cpp submodules/SortFilterProxyModel/filters/rangefilter.h \
		submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/rangefilter.o submodules/SortFilterProxyModel/filters/rangefilter.cpp

build/obj/expressionfilter.o: submodules/SortFilterProxyModel/filters/expressionfilter.cpp submodules/SortFilterProxyModel/filters/expressionfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/expressionfilter.o submodules/SortFilterProxyModel/filters/expressionfilter.cpp

build/obj/filtercontainerfilter.o: submodules/SortFilterProxyModel/filters/filtercontainerfilter.cpp submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filtercontainerfilter.o submodules/SortFilterProxyModel/filters/filtercontainerfilter.cpp

build/obj/anyoffilter.o: submodules/SortFilterProxyModel/filters/anyoffilter.cpp submodules/SortFilterProxyModel/filters/anyoffilter.h \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/anyoffilter.o submodules/SortFilterProxyModel/filters/anyoffilter.cpp

build/obj/alloffilter.o: submodules/SortFilterProxyModel/filters/alloffilter.cpp submodules/SortFilterProxyModel/filters/alloffilter.h \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/alloffilter.o submodules/SortFilterProxyModel/filters/alloffilter.cpp

build/obj/filtersqmltypes.o: submodules/SortFilterProxyModel/filters/filtersqmltypes.cpp submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/filters/valuefilter.h \
		submodules/SortFilterProxyModel/filters/rolefilter.h \
		submodules/SortFilterProxyModel/filters/indexfilter.h \
		submodules/SortFilterProxyModel/filters/regexpfilter.h \
		submodules/SortFilterProxyModel/filters/rangefilter.h \
		submodules/SortFilterProxyModel/filters/expressionfilter.h \
		submodules/SortFilterProxyModel/filters/anyoffilter.h \
		submodules/SortFilterProxyModel/filters/filtercontainerfilter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/alloffilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filtersqmltypes.o submodules/SortFilterProxyModel/filters/filtersqmltypes.cpp

build/obj/sorter.o: submodules/SortFilterProxyModel/sorters/sorter.cpp submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sorter.o submodules/SortFilterProxyModel/sorters/sorter.cpp

build/obj/sortercontainer.o: submodules/SortFilterProxyModel/sorters/sortercontainer.cpp submodules/SortFilterProxyModel/sorters/sortercontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sortercontainer.o submodules/SortFilterProxyModel/sorters/sortercontainer.cpp

build/obj/rolesorter.o: submodules/SortFilterProxyModel/sorters/rolesorter.cpp submodules/SortFilterProxyModel/sorters/rolesorter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/rolesorter.o submodules/SortFilterProxyModel/sorters/rolesorter.cpp

build/obj/stringsorter.o: submodules/SortFilterProxyModel/sorters/stringsorter.cpp submodules/SortFilterProxyModel/sorters/stringsorter.h \
		submodules/SortFilterProxyModel/sorters/rolesorter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/stringsorter.o submodules/SortFilterProxyModel/sorters/stringsorter.cpp

build/obj/expressionsorter.o: submodules/SortFilterProxyModel/sorters/expressionsorter.cpp submodules/SortFilterProxyModel/sorters/expressionsorter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/expressionsorter.o submodules/SortFilterProxyModel/sorters/expressionsorter.cpp

build/obj/sortersqmltypes.o: submodules/SortFilterProxyModel/sorters/sortersqmltypes.cpp submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/sorters/rolesorter.h \
		submodules/SortFilterProxyModel/sorters/stringsorter.h \
		submodules/SortFilterProxyModel/sorters/filtersorter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/expressionsorter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/sortersqmltypes.o submodules/SortFilterProxyModel/sorters/sortersqmltypes.cpp

build/obj/proxyrole.o: submodules/SortFilterProxyModel/proxyroles/proxyrole.cpp submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/filters/filter.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/proxyrole.o submodules/SortFilterProxyModel/proxyroles/proxyrole.cpp

build/obj/proxyrolecontainer.o: submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.cpp submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/proxyrolecontainer.o submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.cpp

build/obj/joinrole.o: submodules/SortFilterProxyModel/proxyroles/joinrole.cpp submodules/SortFilterProxyModel/proxyroles/joinrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/joinrole.o submodules/SortFilterProxyModel/proxyroles/joinrole.cpp

build/obj/switchrole.o: submodules/SortFilterProxyModel/proxyroles/switchrole.cpp submodules/SortFilterProxyModel/proxyroles/switchrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h \
		submodules/SortFilterProxyModel/filters/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/switchrole.o submodules/SortFilterProxyModel/proxyroles/switchrole.cpp

build/obj/expressionrole.o: submodules/SortFilterProxyModel/proxyroles/expressionrole.cpp submodules/SortFilterProxyModel/proxyroles/expressionrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/expressionrole.o submodules/SortFilterProxyModel/proxyroles/expressionrole.cpp

build/obj/proxyrolesqmltypes.o: submodules/SortFilterProxyModel/proxyroles/proxyrolesqmltypes.cpp submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/proxyroles/joinrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/switchrole.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/expressionrole.h \
		submodules/SortFilterProxyModel/proxyroles/regexprole.h \
		submodules/SortFilterProxyModel/proxyroles/filterrole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/proxyrolesqmltypes.o submodules/SortFilterProxyModel/proxyroles/proxyrolesqmltypes.cpp

build/obj/singlerole.o: submodules/SortFilterProxyModel/proxyroles/singlerole.cpp submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/singlerole.o submodules/SortFilterProxyModel/proxyroles/singlerole.cpp

build/obj/regexprole.o: submodules/SortFilterProxyModel/proxyroles/regexprole.cpp submodules/SortFilterProxyModel/proxyroles/regexprole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/qqmlsortfilterproxymodel.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/sorters/sortercontainer.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrolecontainer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/regexprole.o submodules/SortFilterProxyModel/proxyroles/regexprole.cpp

build/obj/filtersorter.o: submodules/SortFilterProxyModel/sorters/filtersorter.cpp submodules/SortFilterProxyModel/sorters/filtersorter.h \
		submodules/SortFilterProxyModel/sorters/sorter.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filtersorter.o submodules/SortFilterProxyModel/sorters/filtersorter.cpp

build/obj/filterrole.o: submodules/SortFilterProxyModel/proxyroles/filterrole.cpp submodules/SortFilterProxyModel/proxyroles/filterrole.h \
		submodules/SortFilterProxyModel/proxyroles/singlerole.h \
		submodules/SortFilterProxyModel/proxyroles/proxyrole.h \
		submodules/SortFilterProxyModel/filters/filtercontainer.h \
		submodules/SortFilterProxyModel/filters/filter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/filterrole.o submodules/SortFilterProxyModel/proxyroles/filterrole.cpp

build/obj/moc_qqmlsortfilterproxymodel.o: build/moc/moc_qqmlsortfilterproxymodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_qqmlsortfilterproxymodel.o build/moc/moc_qqmlsortfilterproxymodel.cpp

build/obj/moc_filter.o: build/moc/moc_filter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_filter.o build/moc/moc_filter.cpp

build/obj/moc_rolefilter.o: build/moc/moc_rolefilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_rolefilter.o build/moc/moc_rolefilter.cpp

build/obj/moc_valuefilter.o: build/moc/moc_valuefilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_valuefilter.o build/moc/moc_valuefilter.cpp

build/obj/moc_indexfilter.o: build/moc/moc_indexfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_indexfilter.o build/moc/moc_indexfilter.cpp

build/obj/moc_regexpfilter.o: build/moc/moc_regexpfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_regexpfilter.o build/moc/moc_regexpfilter.cpp

build/obj/moc_rangefilter.o: build/moc/moc_rangefilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_rangefilter.o build/moc/moc_rangefilter.cpp

build/obj/moc_expressionfilter.o: build/moc/moc_expressionfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_expressionfilter.o build/moc/moc_expressionfilter.cpp

build/obj/moc_filtercontainerfilter.o: build/moc/moc_filtercontainerfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_filtercontainerfilter.o build/moc/moc_filtercontainerfilter.cpp

build/obj/moc_anyoffilter.o: build/moc/moc_anyoffilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_anyoffilter.o build/moc/moc_anyoffilter.cpp

build/obj/moc_alloffilter.o: build/moc/moc_alloffilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_alloffilter.o build/moc/moc_alloffilter.cpp

build/obj/moc_sorter.o: build/moc/moc_sorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_sorter.o build/moc/moc_sorter.cpp

build/obj/moc_rolesorter.o: build/moc/moc_rolesorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_rolesorter.o build/moc/moc_rolesorter.cpp

build/obj/moc_stringsorter.o: build/moc/moc_stringsorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_stringsorter.o build/moc/moc_stringsorter.cpp

build/obj/moc_expressionsorter.o: build/moc/moc_expressionsorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_expressionsorter.o build/moc/moc_expressionsorter.cpp

build/obj/moc_proxyrole.o: build/moc/moc_proxyrole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_proxyrole.o build/moc/moc_proxyrole.cpp

build/obj/moc_joinrole.o: build/moc/moc_joinrole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_joinrole.o build/moc/moc_joinrole.cpp

build/obj/moc_switchrole.o: build/moc/moc_switchrole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_switchrole.o build/moc/moc_switchrole.cpp

build/obj/moc_expressionrole.o: build/moc/moc_expressionrole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_expressionrole.o build/moc/moc_expressionrole.cpp

build/obj/moc_singlerole.o: build/moc/moc_singlerole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_singlerole.o build/moc/moc_singlerole.cpp

build/obj/moc_regexprole.o: build/moc/moc_regexprole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_regexprole.o build/moc/moc_regexprole.cpp

build/obj/moc_filtersorter.o: build/moc/moc_filtersorter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_filtersorter.o build/moc/moc_filtersorter.cpp

build/obj/moc_filterrole.o: build/moc/moc_filterrole.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_filterrole.o build/moc/moc_filterrole.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

